input {
  kafka {
    bootstrap_servers => "localhost:9092" 
    topics => ["filebeat"] # 토픽
    group_id => "logstash_group" # Kafka consumer 그룹 ID
  }

output {
  elasticsearch {
    hosts => ["http://localhost:9200"] # Elasticsearch의 주소
    index => "your_index_name" # 저장할 Elasticsearch 인덱스 이름
    document_id => "%{[@metadata][kafka_offset]}" # 문서의 고유 ID
  }
}
}
