- pipeline.id: container_logs_pipeline
  path.config: "/usr/share/logstash/pipeline/container-logs.conf"
- pipeline.id: instagram_profiles_pipeline
  path.config: "/usr/share/logstash/pipeline/instagram-profiles.conf"
